# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: Test dosega na docker.test
  hosts: docker.test
  become: true
 
  tasks:
  - name: login
    command: sudo docker login -u andrej.ursnik1 -p {{ andrej_gitlab_secret }} docker.osi.si
    
  - name: pull image
    command: sudo docker pull docker.osi.si/docker/java:latest
  

