---
# tasks file for /test-ansible/roles/prenos-slike
#test

  - name: login to srchub
    command: sudo docker login -u andrej.ursnik1 -p {{ andrej_gitlab_secret }} docker.osi.si
    
  - name: pull image
    command: sudo docker pull docker.osi.si/docker/java:latest
    
  - name: save image to .tar
    command: sudo docker save -o /test-ansible/files/images/java-latest.tar docker.osi.si/docker/java:latest
  
  - name: delete imagee java
    command: sudo docker image rm docker.osi.si/docker/java:latest

  - name: change owner of .tar
    command: sudo chown root:osiadm /test-ansible/files/images/java-latest.tar
    
  - name: change permission of .tar
    command: sudo chmod 0660 /test-ansible/files/images/java-latest.tar
